version: "2"
services:
  choosecoders_backend_latest:
    build:
      context: ../backend/.
      dockerfile: Dockerfile
    #image: nryabkov/myrepository:choosecoders_backend_latest
    #container_name: choosecoders_backend_latest
    ports:
      - 3006:3006
  choosecoders_frontend_latest:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: choosecoders_frontend_latest
    ports:
      - 80:80
      - 443:443
    links:
      - choosecoders_backend_latest
